services:
  - type: web
    name: foodbank-maastricht-website
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
